/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JOZE RODRIGUEZ
 */
public class ConsPacientesInternalFrame extends javax.swing.JInternalFrame {

    public controlador.GestorPacienteControl gestorPacienteControl;
    private DefaultTableModel tabla;
    
    public ConsPacientesInternalFrame() {
        initComponents();
        gestorPacienteControl=new  controlador.GestorPacienteControl(this);
        String titulosTabla[]={"Identificacion","Nombres","Apeliidos","Fecha nacimiento","Genero"};
        tabla=new DefaultTableModel(null,titulosTabla);
        tblDatos.setModel(tabla);
        btnAceptar.addActionListener(gestorPacienteControl);
       
        
    }
    public DefaultTableModel getTablaModel(){
        return tabla;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rdbIdentifiacion = new javax.swing.JRadioButton();
        rdbNombres = new javax.swing.JRadioButton();
        rdbGenero = new javax.swing.JRadioButton();
        rdbApellidos = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();

        buttonGroup1.add(rdbIdentifiacion);
        rdbIdentifiacion.setText("Identificacion");

        buttonGroup1.add(rdbNombres);
        rdbNombres.setText("Nombres");

        buttonGroup1.add(rdbGenero);
        rdbGenero.setText("Sexo");

        rdbApellidos.setText("Apellidos");

        jLabel1.setText("Valor a buscar:");

        txtValor.setName("ValorTxt"); // NOI18N

        btnAceptar.setText("Aceptar");
        btnAceptar.setName("AceptarBtn"); // NOI18N

        jScrollPane1.setName("ResultadosTbl"); // NOI18N

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDatos.setName("ResultadosBtn"); // NOI18N
        jScrollPane1.setViewportView(tblDatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdbIdentifiacion)
                        .addGap(18, 18, 18)
                        .addComponent(rdbNombres)
                        .addGap(18, 18, 18)
                        .addComponent(rdbApellidos)
                        .addGap(18, 18, 18)
                        .addComponent(rdbGenero))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(22, 22, 22)
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAceptar)))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbIdentifiacion)
                    .addComponent(rdbNombres)
                    .addComponent(rdbApellidos)
                    .addComponent(rdbGenero))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAceptar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JRadioButton rdbApellidos;
    public javax.swing.JRadioButton rdbGenero;
    public javax.swing.JRadioButton rdbIdentifiacion;
    public javax.swing.JRadioButton rdbNombres;
    public javax.swing.JTable tblDatos;
    public javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
